/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDadosEmpresaRouteImport } from './routes/_authenticated/dados-empresa'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedRelatoriosSalvosRouteImport } from './routes/_authenticated/relatorios-salvos'
import { Route as AuthenticatedValoresRouteImport } from './routes/_authenticated/valores'
import { Route as AuthenticatedApontamentoIdRouteImport } from './routes/_authenticated/apontamento.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDadosEmpresaRoute =
  AuthenticatedDadosEmpresaRouteImport.update({
    id: '/dados-empresa',
    path: '/dados-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosSalvosRoute =
  AuthenticatedRelatoriosSalvosRouteImport.update({
    id: '/relatorios-salvos',
    path: '/relatorios-salvos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValoresRoute = AuthenticatedValoresRouteImport.update({
  id: '/valores',
  path: '/valores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApontamentoIdRoute =
  AuthenticatedApontamentoIdRouteImport.update({
    id: '/apontamento/$id',
    path: '/apontamento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dados-empresa': typeof AuthenticatedDadosEmpresaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/relatorios-salvos': typeof AuthenticatedRelatoriosSalvosRoute
  '/valores': typeof AuthenticatedValoresRoute
  '/apontamento/$id': typeof AuthenticatedApontamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dados-empresa': typeof AuthenticatedDadosEmpresaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/relatorios-salvos': typeof AuthenticatedRelatoriosSalvosRoute
  '/valores': typeof AuthenticatedValoresRoute
  '/apontamento/$id': typeof AuthenticatedApontamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dados-empresa': typeof AuthenticatedDadosEmpresaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/relatorios-salvos': typeof AuthenticatedRelatoriosSalvosRoute
  '/_authenticated/valores': typeof AuthenticatedValoresRoute
  '/_authenticated/apontamento/$id': typeof AuthenticatedApontamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/clientes'
    | '/dados-empresa'
    | '/historico'
    | '/mais'
    | '/novo'
    | '/orcamento'
    | '/orcamentos'
    | '/painel'
    | '/pecas'
    | '/relatorio'
    | '/relatorios-salvos'
    | '/valores'
    | '/apontamento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/clientes'
    | '/dados-empresa'
    | '/historico'
    | '/mais'
    | '/novo'
    | '/orcamento'
    | '/orcamentos'
    | '/painel'
    | '/pecas'
    | '/relatorio'
    | '/relatorios-salvos'
    | '/valores'
    | '/apontamento/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/clientes'
    | '/_authenticated/dados-empresa'
    | '/_authenticated/historico'
    | '/_authenticated/mais'
    | '/_authenticated/novo'
    | '/_authenticated/orcamento'
    | '/_authenticated/orcamentos'
    | '/_authenticated/painel'
    | '/_authenticated/pecas'
    | '/_authenticated/relatorio'
    | '/_authenticated/relatorios-salvos'
    | '/_authenticated/valores'
    | '/_authenticated/apontamento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dados-empresa': {
      id: '/_authenticated/dados-empresa'
      path: '/dados-empresa'
      fullPath: '/dados-empresa'
      preLoaderRoute: typeof AuthenticatedDadosEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios-salvos': {
      id: '/_authenticated/relatorios-salvos'
      path: '/relatorios-salvos'
      fullPath: '/relatorios-salvos'
      preLoaderRoute: typeof AuthenticatedRelatoriosSalvosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valores': {
      id: '/_authenticated/valores'
      path: '/valores'
      fullPath: '/valores'
      preLoaderRoute: typeof AuthenticatedValoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apontamento/$id': {
      id: '/_authenticated/apontamento/$id'
      path: '/apontamento/$id'
      fullPath: '/apontamento/$id'
      preLoaderRoute: typeof AuthenticatedApontamentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDadosEmpresaRoute: typeof AuthenticatedDadosEmpresaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedRelatoriosSalvosRoute: typeof AuthenticatedRelatoriosSalvosRoute
  AuthenticatedValoresRoute: typeof AuthenticatedValoresRoute
  AuthenticatedApontamentoIdRoute: typeof AuthenticatedApontamentoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDadosEmpresaRoute: AuthenticatedDadosEmpresaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedRelatoriosSalvosRoute: AuthenticatedRelatoriosSalvosRoute,
  AuthenticatedValoresRoute: AuthenticatedValoresRoute,
  AuthenticatedApontamentoIdRoute: AuthenticatedApontamentoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
